### ISSUE TITLE
AspectObjectDumper Nuget package is built against .net 4.6.1

### ISSUE THREAD

**Issue by killergege** [vmelamed/vm#1]
Hi, sorry to bother again.
The new version of the Nuget package is now built against the version 4.6.1 of the .net framework so my project doesn't compile anymore after updating packages.
I'm using .net 4.5, but the Nuget description says it targets .net 4.0.

I'm pretty sure I tested it after you closed the issues I submitted so I guess you've built a new Nuget package since.

**Comment by vmelamed** [comment]
Thank you.
Val

**Comment by piyushchauhan2011** [comment]
Library is really cool 👍  Any updates on supporting for `.netcore1.0` @vmelamed ?

**Comment by vmelamed** [comment]
Ah, yes .netcore... I'm sorry, I wish I had the time but I'm buried right now. The big problem is that afaik .netcore got rid of a lot of reflection functionality and as I mentioned in the documentation the object dumper is really one big exercise on reflection, so I'm afraid it will not be trivial. Definitely need work there.
