### ISSUE TITLE
Dump results to Json or List

### ISSUE THREAD

**Issue by tb-mtg** [vmelamed/vm#3]
Love this utility!! 

However would it be possible to dump the results to json serialized string format and/or to nested lists rather than just indented?

**Comment by vmelamed** [comment]
Thank you.

I thought about dumping to JSON but for now I would prefer using Newtonsoft - this is the greatest JSON lib out there and I cannot imagine that I can do better than these guys.
I am afraid I don't understand what is "nested list", can you please elaborate?

I suppose you want to be able to process logs created with the help of the Object Dumper. I would not recommend it - Object Dumper was always meant for developer's easy reading. Most importantly I am afraid that on a massive scale the performance would not be satisfactory. Again in a case like this I would use Newtonsoft.

Val
