### ISSUE TITLE
Allow all array elements to be logged

### ISSUE THREAD

**Issue by davidaramant** [vmelamed/vm#5]
For my use case, printing all the elements of an array instead of just the first ten would be useful.  This seems like it could be passed in as a constructor parameter to `ObjectDumper`.

**Comment by vmelamed** [comment]
Try putting an attribute like this [Dump(MaxLength = -1)].

Thanks.
Val

**Comment by davidaramant** [comment]
The scenario I was using it for was for a class in an API that I do not control.  I can't add attributes to it.

**Comment by vmelamed** [comment]
Actually you can. Look at the signature of the method: it has a System.Type parameter called dumpMetadata where you can supply a buddy class explicitly like this:



class Object7_1

{

    public Object7_1()

    {

        Property1 = "Property1";

        Property2 = "Property2";

        List = new List<int> { 0, 1, 2, 3, 4, 5, };

    }



    public string Property1 { get; set; }

    public string Property2 { get; set; }

    public List<int> List { get; set; }

}



abstract class MetaObject7_1

{

    public string Property1 { get; set; }

    public string Property2 { get; set; }

    [Dump(MaxLength = -1)]

    public List<int> List { get; set; }

}



        [TestMethod]

        public void TestDumpObject7_1_3()

        {

            using (var w = new StringWriter(CultureInfo.InvariantCulture))

            {

                var target = new ObjectTextDumper(w);

                var test = new Object7_1

                {

                    List = new List<int> { 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, },

                };

                var expected = @"

Object7_1 (vm.Aspects.Diagnostics.ObjectDumper.Tests.ObjectTextDumperTest+Object7_1, vm.Aspects.Diagnostics.ObjectDumper.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1fb2eb0544466393):

  List                     = List<int>[18]: (System.Collections.Generic.List`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)

    0

    1

    2

    3

    4

    5

    0

    1

    2

    3

    4

    5

    0

    1

    2

    3

    4

    5

  Property1                = Property1

  Property2                = Property2";



                target.Dump(test, typeof(MetaObject7_1));



                var actual = w.GetStringBuilder().ToString();



                TestContext.WriteLine("{0}", actual);

                Assert.AreEqual(expected, actual);

            }

        }


You can also supply a third parameter which is a class-wide DumpAttribute.

Thank you.
Val
